language: node_js
os:
  - linux
  - osx
node_js:
  - '5.3.0'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install'

after_script:
  - 'make test'
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage'
env:
  - NO_SERIALPORT_INSTALL=1
